import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import PublicView from "@/components/HOC/PublicView";
import Hero from "@/components/Hero/Hero";
import Category from "@/components/Category/Category";
import Advertisement from "@/components/Advertisements/Advertisement";
import Blog from "@/components/Blog/Blog";
import Event from "@/components/Event/Event";
import Partner from "@/components/Partner/Partner";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

const  Home = () => {
  
  return (
    <>
      <Head>
        <title>Welcome | 2nd A Friendly</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <>
       <Hero />
       <Category />
       <Advertisement />
       <Blog />
       <Event />
       <Partner />
      </>
    </>
  );
}

export default PublicView(Home)
